public class Main {
    public static void main(String[] args) {
        Peasant peasant1 = new Peasant();
        peasant1.name = "Hans";
        Peasant peasant2 = new Peasant();
        peasant2.name = "Alls";
        Peasant peasant3 = new Peasant();
        peasant3.name = "Cristof";
        Peasant peasant4 = new Peasant();
        peasant4.name = "Vollen";
        Peasant peasant5 = new Peasant();
        peasant5.name = "Karl";
        Robber robber1 = new Robber();
        Robber robber2 = new Robber();
        Robber robber3 = new Robber();
        Robber robber4 = new Robber();
        Robber robber5 = new Robber();
        Sniper sniper1 = new Sniper();
        Sniper sniper2 = new Sniper();
        Sniper sniper3 = new Sniper();
        Sniper sniper4 = new Sniper();
        Sniper sniper5 = new Sniper();
        Wizard wizard1 = new Wizard();
        Wizard wizard2 = new Wizard();
        Wizard wizard3 = new Wizard();
        Wizard wizard4 = new Wizard();
        Wizard wizard5 = new Wizard();
        Spearman spearman1 = new Spearman();
        Spearman spearman2 = new Spearman();
        Spearman spearman3 = new Spearman();
        Spearman spearman4 = new Spearman();
        Spearman spearman5 = new Spearman();
        Arbalester arbalester1 = new Arbalester();
        Arbalester arbalester2 = new Arbalester();
        Arbalester arbalester3 = new Arbalester();
        Arbalester arbalester4 = new Arbalester();
        Arbalester arbalester5 = new Arbalester();
        Monk monk1 = new Monk();
        Monk monk2 = new Monk();
        Monk monk3 = new Monk();
        Monk monk4 = new Monk();
        Monk monk5 = new Monk();

        peasant1.print();
        peasant2.print();
        peasant3.print();
        peasant4.print();
        peasant5.print();
        robber1.print();
        robber2.print();
        robber3.print();
        robber4.print();
        robber5.print();
        sniper1.print();
        sniper2.print();
        sniper3.print();
        sniper4.print();
        sniper5.print();
        wizard1.print();
        wizard2.print();
        wizard3.print();
        wizard4.print();
        wizard5.print();
        spearman1.print();
        spearman2.print();
        spearman3.print();
        spearman4.print();
        spearman5.print();
        arbalester1.print();
        arbalester2.print();
        arbalester3.print();
        arbalester4.print();
        arbalester5.print();
        monk1.print();
        monk2.print();
        monk3.print();
        monk4.print();
        monk5.print();
    }
}
